apiVersion: v1
kind: Service
metadata:
  name: my-app-backend
  labels:
    app: my-app-backend
spec:
  selector:
    app: my-app-backend
  type: NodePort
  ports:
    - name: back-http-port
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-backend
  labels:
    app: my-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-backend
  template:
    metadata:
      labels:
        app: my-app-backend
    spec:
      containers:
        - name: my-app-back-nginx
          image: hdys/my-app-back-nginx
          env:
            - name: NGINX_LISTEN_PORT
              value: "80"
            - name: BACKEND_PORT
              value: http://localhost:8080
          ports:
            - containerPort: 80

        - name: my-app-go-app
          image: hdys/my-app-go-app
          env:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: go_app_db
            - name: POSTGRES_DB_ENDPOINT
              value: http://postgres:5432
          ports:
            - containerPort: 8080
