apiVersion: v1
kind: Service
metadata:
  name: my-app-front-nginx
  labels:
    app: my-app-front-nginx
spec:
  type: LoadBalancer
  ports:
    - name: front-http-port
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: my-app-front-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-front-nginx
  labels:
    app: my-app-front-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-front-nginx
  template:
    metadata:
      labels:
        app: my-app-front-nginx
    spec:
      containers:
        - name: my-app-front-nginx
          image: hdys/my-app-front-nginx
          env:
            - name: NGINX_LISTEN_PORT
              value: "80"
            - name: BACKEND_PORT
              value: http://my-app-backend:80
          ports:
            - containerPort: 80
